Add controller for PATCH request
Himasnhu-AT/Blogs pull request #12
Opened 2024-07-12 15:10 UTC by Swastik19Nit

solves  issue #14

2024-07-14 01:12 UTC, Himasnhu-AT requested changes
resolve these conversations

2024-07-14 01:12 UTC, Himasnhu-AT commented on server/src/controllers/blog-controller.js
> +        const id=req.params.id;
try to concise this

2024-07-14 01:12 UTC, Himasnhu-AT commented on server/src/controllers/blog-controller.js
> +    {
use this type of format: try {

ensure `{` is in same line, reducing the number of lines

2024-07-14 01:12 UTC, Himasnhu-AT commented on server/src/controllers/blog-controller.js
> +        return res.status(500).json({message:"Error while updating Blog",error: error.message})
dont send error to fronend api as it is. Do proper sanitization or just console.error the message, and send `INTERNAL SERVER FAILURE` or something like that

2024-07-14 03:58 UTC, Swastik19Nit commented
@Himasnhu-AT

2024-07-20 06:59 UTC, Himasnhu-AT approved these changes

2024-07-20 06:59 UTC, merged