Newsletter Mail Feature with models
Himasnhu-AT/Blogs pull request #2
Opened 2024-06-28 15:40 UTC by mayank2393

2024-06-28 16:01 UTC, Himasnhu-AT requested changes
Resolve following issues

2024-06-28 16:01 UTC, Himasnhu-AT commented on server/src/controllers/newsletter.js
> +    })
Send it as BCC, don't send them in a loop

2024-06-28 16:01 UTC, Himasnhu-AT commented on server/src/router/newsletter.js
Cleanup file

2024-06-28 16:01 UTC, Himasnhu-AT commented on server/src/router/newsletter.js
i mean remove unnecessary comments, lint it

2024-06-28 16:02 UTC, Himasnhu-AT commented
@mayank2393 @ArnavSharma005, no need to close pr, just commit int branch and push, it'll automatically combine in this only

2024-06-28 16:03 UTC, Himasnhu-AT commented on server/src/router/newsletter.js
> +})
Implemented on later stage

2024-06-29 07:24 UTC, Debatreya commented
@Himasnhu-AT isse aj merge krde
Bakio o ko models chahiye honge

2024-06-29 07:26 UTC, Himasnhu-AT approved these changes

2024-06-29 07:26 UTC, merged

2024-06-29 07:27 UTC, Himasnhu-AT commented
@Debatreya hogya