Review blog
Himasnhu-AT/Blogs pull request #3
Opened 2024-07-06 19:48 UTC by RiyaRaj28

Added logic for blog review by admin.

2024-07-06 21:38 UTC, Himasnhu-AT requested changes
Complete the comments below to make it working. Also check proper functionality by imitating server operation by hardcoding things

2024-07-06 21:38 UTC, Himasnhu-AT commented on server/src/controllers/blog-review.js
> +  const user = req.user;
implemented in a later stage, not required right now. Will cause the api to fail

2024-07-06 21:38 UTC, Himasnhu-AT commented on server/src/controllers/blog-review.js
> +      break;
will cause server to crash

2024-07-06 21:38 UTC, Himasnhu-AT commented on server/src/controllers/blog-review.js
> +      break;
crashing server

2024-07-06 21:38 UTC, Himasnhu-AT commented on server/src/controllers/blog-review.js
> +  res.json({ message: 'Blog review updated successfully' });
won't even reach this line. as response is already allocated above

2024-07-06 21:38 UTC, Himasnhu-AT commented on server/src/model/blog.js
> +import Tag from './tags.js'
follow the proper linting method.  enter after function change for making reading easier

2024-07-07 01:55 UTC, Debatreya commented
@Himasnhu-AT 
Folder structure as discussed by.us.
Usme hum src/routes mein hi controller likh rhe the
 and src/routes/routes.js mein route declare kr rhe the. 

Ig we should get rid of the src/controller.

Bta dena.
Mere issue wala kaam ho jaay, 
Mein structure theek kr dunga.

2024-07-07 05:38 UTC, RiyaRaj28 commented
> @RiyaRaj28 Complete the comments below to make it working. Also check proper functionality by imitating server operation by hardcoding things
> 
> Resolving [Issue 16](https://github.com/technobyte-nitkkr/Blogs/issues/16#issue-2321551649).



> @RiyaRaj28 Complete the comments below to make it working. Also check proper functionality by imitating server operation by hardcoding things
> 
> Resolving [Issue 16](https://github.com/technobyte-nitkkr/Blogs/issues/16#issue-2321551649).

Okay.

2024-07-07 10:08 UTC, Himasnhu-AT requested changes
Great Work!

### UPDATE: 
When setting `reviewStatus` to update, make sure message is provided and is not undefined

API CALL:

- Request: 
```bash
ssh:OpenEdu_AI_test Blogs % curl -X POST http://localhost:3000/admin/blog/review/668a67885a968b26ecb519a5 -H "Content-Type: application/json" -d '{"reviewStatus": "update"}' 
```
- Response:
```json
{
  "message": "Blog requires updates. Please review the comments: undefined",
  "updatedBlog": {
    "_id": "668a67885a968b26ecb519a5",
    "title": "My New Blog",
    "content": "This is my new blog content",
    "image": "https://example.com/image.jpg",
    "review": "update",
    "tags": [],
    "comments": [],
    "__v": 0
  }
}
```

2024-07-07 10:13 UTC, Himasnhu-AT commented
Also, convert `admin/blog` API to `seed`

@Debatreya, Let's keep this function to seed the data. Let other know to enter the seed for testing purposes.

2024-07-07 10:18 UTC, Debatreya commented
Raat ko call krta hu

2024-07-08 15:38 UTC, Himasnhu-AT approved these changes

2024-07-08 15:38 UTC, merged